# Generated by Django 5.0.6 on 2024-06-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindcraftweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://img.freepik.com/vector-premium/icono-perfil-usuario-estilo-plano-ilustracion-vector-avatar-miembro-sobre-fondo-aislado-concepto-negocio-signo-permiso-humano_157943-15752.jpg', upload_to=''),
        ),
    ]
